### ISSUE TITLE
miss some java files?

### ISSUE THREAD

**Issue by liu2510865** [diegocairone/olingo-odata4-jpa-ext#1]
hi:

i clone this project ,have some error,please check it.

![image](https://user-images.githubusercontent.com/4935445/33000082-d670cda8-cde0-11e7-8c3e-a6cf3b35aa37.png)

it is  look like some java file miss...

**Comment by diegocairone** [comment]
That is correct but classes starting with Q are auto-generated through a MAVEN plugin: look into pom.xml between lines 85 and 113. This is because this example app depends on QueryDSL (www.querydsl.com).
I suggest you check out "olingo-ext-demo" module as a better example for using this Apache Olingo library extension.
